### ISSUE TITLE
Unsafe use of system allows command execution

### ISSUE THREAD

**Issue by cym13** [nrosvall/libsteel#1]
Description
===========

It is possible to abuse db_shred from database.c to execute arbitrary shell code.

Problems
========

No input validation is done and no escaping is performed on the filename

How to reproduce
================

steel uses this function when shredding (-R):

    $ steel -R ';uname -a'
    Failed to open file
    Are you sure? (y/N) y
    shred: missing file operand
    Try 'shred --help' for more information.
    Linux dashie 4.4.5-1-ARCH #1 SMP PREEMPT Thu Mar 10 07:54:30 CET 2016 i686 GNU/Linux

Note that the file doesn't exist but it could have, input validation alone doesn't solve the problem.

Version
=======

      $ steel --version
      Steel v1.3 Copyright (c) Niko Rosvall <niko@byteptr.com>
      This is free software; see the source for copying conditions.
      There is no warranty; not even for MERCHANTABILITY or FITNESS
      FOR A PARTICULAR PURPOSE.

      $ cd libsteel | git log --oneline | head -1
      690add6 Fix function declaration syntax.

**Comment by nrosvall** [comment]
Hi thanks for the report. Sorry, for some reason Github notified me just now about this issue. I will look into this as soon as possible. This seems to be valid problem, I agree.

**Comment by nrosvall** [comment]
Shred usage is now removed. It's not effective on SDD drives anyway which are more and more common. Just using remove() for now. I would like to have some real solution (which also works on SDDs)
